.TH "RADO\-SEARCH" "1" "April 2015" "" ""
.SH "NAME"
\fBrado-search\fR \- search for shows by title
.SH SYNOPSIS
.P
.RS 2
.nf
rado search <search_term>
.fi
.RE
.SH DESCRIPTION
.P
This command does what it says on the tin: it searches for shows by title\. This
is useful to find a show if you only remember part of the title, and especially
useful to get the slug for \fBrado download\fR
.SH EXAMPLES
.P
Search for shows with "shoot" in the title
.P
.RS 2
.nf
$ rado search shoot
.fi
.RE
.P
Serach for Space Patrol
.P
.RS 2
.nf
$ rado search "space patrol"
.fi
.RE
